run:
  timeout: 5m
  go: '1.24'

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - revive
    - gocritic
    - gosec

linters-settings:
  revive:
    rules:
      - name: exported
        disabled: true
  gosec:
    excludes:
      - G404 # Weak random number generator
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance

issues:
  exclude-rules:
    # Exclude generated protobuf files
    - path: "api/.*\\.pb\\.go$"
      linters:
        - all
    # Exclude test files from certain linters
    - path: "_test\\.go$"
      linters:
        - gosec
        - gocritic
