// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.1
// source: api/v1/ticketscoring.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TimePeriodRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartDate     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimePeriodRequest) Reset() {
	*x = TimePeriodRequest{}
	mi := &file_api_v1_ticketscoring_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimePeriodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimePeriodRequest) ProtoMessage() {}

func (x *TimePeriodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_ticketscoring_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimePeriodRequest.ProtoReflect.Descriptor instead.
func (*TimePeriodRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_ticketscoring_proto_rawDescGZIP(), []int{0}
}

func (x *TimePeriodRequest) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *TimePeriodRequest) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

type OverallQualityScoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Score         float64                `protobuf:"fixed64,1,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OverallQualityScoreResponse) Reset() {
	*x = OverallQualityScoreResponse{}
	mi := &file_api_v1_ticketscoring_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OverallQualityScoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OverallQualityScoreResponse) ProtoMessage() {}

func (x *OverallQualityScoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_ticketscoring_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OverallQualityScoreResponse.ProtoReflect.Descriptor instead.
func (*OverallQualityScoreResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_ticketscoring_proto_rawDescGZIP(), []int{1}
}

func (x *OverallQualityScoreResponse) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

type PeriodScore struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Period        string                 `protobuf:"bytes,1,opt,name=period,proto3" json:"period,omitempty"`
	Score         float64                `protobuf:"fixed64,2,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeriodScore) Reset() {
	*x = PeriodScore{}
	mi := &file_api_v1_ticketscoring_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeriodScore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeriodScore) ProtoMessage() {}

func (x *PeriodScore) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_ticketscoring_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeriodScore.ProtoReflect.Descriptor instead.
func (*PeriodScore) Descriptor() ([]byte, []int) {
	return file_api_v1_ticketscoring_proto_rawDescGZIP(), []int{2}
}

func (x *PeriodScore) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

func (x *PeriodScore) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

type TicketScore struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TicketId       int64                  `protobuf:"varint,1,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	CategoryScores map[string]float64     `protobuf:"bytes,2,rep,name=category_scores,json=categoryScores,proto3" json:"category_scores,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TicketScore) Reset() {
	*x = TicketScore{}
	mi := &file_api_v1_ticketscoring_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TicketScore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TicketScore) ProtoMessage() {}

func (x *TicketScore) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_ticketscoring_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TicketScore.ProtoReflect.Descriptor instead.
func (*TicketScore) Descriptor() ([]byte, []int) {
	return file_api_v1_ticketscoring_proto_rawDescGZIP(), []int{3}
}

func (x *TicketScore) GetTicketId() int64 {
	if x != nil {
		return x.TicketId
	}
	return 0
}

func (x *TicketScore) GetCategoryScores() map[string]float64 {
	if x != nil {
		return x.CategoryScores
	}
	return nil
}

type ScoresByTicketResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TicketScores  []*TicketScore         `protobuf:"bytes,1,rep,name=ticket_scores,json=ticketScores,proto3" json:"ticket_scores,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScoresByTicketResponse) Reset() {
	*x = ScoresByTicketResponse{}
	mi := &file_api_v1_ticketscoring_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoresByTicketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoresByTicketResponse) ProtoMessage() {}

func (x *ScoresByTicketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_ticketscoring_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoresByTicketResponse.ProtoReflect.Descriptor instead.
func (*ScoresByTicketResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_ticketscoring_proto_rawDescGZIP(), []int{4}
}

func (x *ScoresByTicketResponse) GetTicketScores() []*TicketScore {
	if x != nil {
		return x.TicketScores
	}
	return nil
}

type PeriodOverPeriodScoreChangeResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	CurrentPeriodScore  float64                `protobuf:"fixed64,1,opt,name=current_period_score,json=currentPeriodScore,proto3" json:"current_period_score,omitempty"`
	PreviousPeriodScore float64                `protobuf:"fixed64,2,opt,name=previous_period_score,json=previousPeriodScore,proto3" json:"previous_period_score,omitempty"`
	ChangePercentage    float64                `protobuf:"fixed64,3,opt,name=change_percentage,json=changePercentage,proto3" json:"change_percentage,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *PeriodOverPeriodScoreChangeResponse) Reset() {
	*x = PeriodOverPeriodScoreChangeResponse{}
	mi := &file_api_v1_ticketscoring_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeriodOverPeriodScoreChangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeriodOverPeriodScoreChangeResponse) ProtoMessage() {}

func (x *PeriodOverPeriodScoreChangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_ticketscoring_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeriodOverPeriodScoreChangeResponse.ProtoReflect.Descriptor instead.
func (*PeriodOverPeriodScoreChangeResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_ticketscoring_proto_rawDescGZIP(), []int{5}
}

func (x *PeriodOverPeriodScoreChangeResponse) GetCurrentPeriodScore() float64 {
	if x != nil {
		return x.CurrentPeriodScore
	}
	return 0
}

func (x *PeriodOverPeriodScoreChangeResponse) GetPreviousPeriodScore() float64 {
	if x != nil {
		return x.PreviousPeriodScore
	}
	return 0
}

func (x *PeriodOverPeriodScoreChangeResponse) GetChangePercentage() float64 {
	if x != nil {
		return x.ChangePercentage
	}
	return 0
}

type CategoryScore struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	CategoryName         string                 `protobuf:"bytes,1,opt,name=category_name,json=categoryName,proto3" json:"category_name,omitempty"`
	TotalRatings         int64                  `protobuf:"varint,2,opt,name=total_ratings,json=totalRatings,proto3" json:"total_ratings,omitempty"`
	OverallCategoryScore float64                `protobuf:"fixed64,3,opt,name=overall_category_score,json=overallCategoryScore,proto3" json:"overall_category_score,omitempty"`
	PeriodScores         []*PeriodScore         `protobuf:"bytes,4,rep,name=period_scores,json=periodScores,proto3" json:"period_scores,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CategoryScore) Reset() {
	*x = CategoryScore{}
	mi := &file_api_v1_ticketscoring_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryScore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryScore) ProtoMessage() {}

func (x *CategoryScore) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_ticketscoring_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryScore.ProtoReflect.Descriptor instead.
func (*CategoryScore) Descriptor() ([]byte, []int) {
	return file_api_v1_ticketscoring_proto_rawDescGZIP(), []int{6}
}

func (x *CategoryScore) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

func (x *CategoryScore) GetTotalRatings() int64 {
	if x != nil {
		return x.TotalRatings
	}
	return 0
}

func (x *CategoryScore) GetOverallCategoryScore() float64 {
	if x != nil {
		return x.OverallCategoryScore
	}
	return 0
}

func (x *CategoryScore) GetPeriodScores() []*PeriodScore {
	if x != nil {
		return x.PeriodScores
	}
	return nil
}

type AggregatedCategoryScoresResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CategoryScores []*CategoryScore       `protobuf:"bytes,1,rep,name=category_scores,json=categoryScores,proto3" json:"category_scores,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AggregatedCategoryScoresResponse) Reset() {
	*x = AggregatedCategoryScoresResponse{}
	mi := &file_api_v1_ticketscoring_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AggregatedCategoryScoresResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggregatedCategoryScoresResponse) ProtoMessage() {}

func (x *AggregatedCategoryScoresResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_ticketscoring_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggregatedCategoryScoresResponse.ProtoReflect.Descriptor instead.
func (*AggregatedCategoryScoresResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_ticketscoring_proto_rawDescGZIP(), []int{7}
}

func (x *AggregatedCategoryScoresResponse) GetCategoryScores() []*CategoryScore {
	if x != nil {
		return x.CategoryScores
	}
	return nil
}

var File_api_v1_ticketscoring_proto protoreflect.FileDescriptor

const file_api_v1_ticketscoring_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/v1/ticketscoring.proto\x12\x10ticketscoring.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x85\x01\n" +
	"\x11TimePeriodRequest\x129\n" +
	"\n" +
	"start_date\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x125\n" +
	"\bend_date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\"3\n" +
	"\x1bOverallQualityScoreResponse\x12\x14\n" +
	"\x05score\x18\x01 \x01(\x01R\x05score\";\n" +
	"\vPeriodScore\x12\x16\n" +
	"\x06period\x18\x01 \x01(\tR\x06period\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x01R\x05score\"\xc9\x01\n" +
	"\vTicketScore\x12\x1b\n" +
	"\tticket_id\x18\x01 \x01(\x03R\bticketId\x12Z\n" +
	"\x0fcategory_scores\x18\x02 \x03(\v21.ticketscoring.v1.TicketScore.CategoryScoresEntryR\x0ecategoryScores\x1aA\n" +
	"\x13CategoryScoresEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"\\\n" +
	"\x16ScoresByTicketResponse\x12B\n" +
	"\rticket_scores\x18\x01 \x03(\v2\x1d.ticketscoring.v1.TicketScoreR\fticketScores\"\xb8\x01\n" +
	"#PeriodOverPeriodScoreChangeResponse\x120\n" +
	"\x14current_period_score\x18\x01 \x01(\x01R\x12currentPeriodScore\x122\n" +
	"\x15previous_period_score\x18\x02 \x01(\x01R\x13previousPeriodScore\x12+\n" +
	"\x11change_percentage\x18\x03 \x01(\x01R\x10changePercentage\"\xd3\x01\n" +
	"\rCategoryScore\x12#\n" +
	"\rcategory_name\x18\x01 \x01(\tR\fcategoryName\x12#\n" +
	"\rtotal_ratings\x18\x02 \x01(\x03R\ftotalRatings\x124\n" +
	"\x16overall_category_score\x18\x03 \x01(\x01R\x14overallCategoryScore\x12B\n" +
	"\rperiod_scores\x18\x04 \x03(\v2\x1d.ticketscoring.v1.PeriodScoreR\fperiodScores\"l\n" +
	" AggregatedCategoryScoresResponse\x12H\n" +
	"\x0fcategory_scores\x18\x01 \x03(\v2\x1f.ticketscoring.v1.CategoryScoreR\x0ecategoryScores2\xd7\x03\n" +
	"\rTicketScoring\x12l\n" +
	"\x16GetOverallQualityScore\x12#.ticketscoring.v1.TimePeriodRequest\x1a-.ticketscoring.v1.OverallQualityScoreResponse\x12v\n" +
	"\x1bGetAggregatedCategoryScores\x12#.ticketscoring.v1.TimePeriodRequest\x1a2.ticketscoring.v1.AggregatedCategoryScoresResponse\x12b\n" +
	"\x11GetScoresByTicket\x12#.ticketscoring.v1.TimePeriodRequest\x1a(.ticketscoring.v1.ScoresByTicketResponse\x12|\n" +
	"\x1eGetPeriodOverPeriodScoreChange\x12#.ticketscoring.v1.TimePeriodRequest\x1a5.ticketscoring.v1.PeriodOverPeriodScoreChangeResponseB&Z$github.com/godilite/qa-server/api/v1b\x06proto3"

var (
	file_api_v1_ticketscoring_proto_rawDescOnce sync.Once
	file_api_v1_ticketscoring_proto_rawDescData []byte
)

func file_api_v1_ticketscoring_proto_rawDescGZIP() []byte {
	file_api_v1_ticketscoring_proto_rawDescOnce.Do(func() {
		file_api_v1_ticketscoring_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_ticketscoring_proto_rawDesc), len(file_api_v1_ticketscoring_proto_rawDesc)))
	})
	return file_api_v1_ticketscoring_proto_rawDescData
}

var file_api_v1_ticketscoring_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_v1_ticketscoring_proto_goTypes = []any{
	(*TimePeriodRequest)(nil),                   // 0: ticketscoring.v1.TimePeriodRequest
	(*OverallQualityScoreResponse)(nil),         // 1: ticketscoring.v1.OverallQualityScoreResponse
	(*PeriodScore)(nil),                         // 2: ticketscoring.v1.PeriodScore
	(*TicketScore)(nil),                         // 3: ticketscoring.v1.TicketScore
	(*ScoresByTicketResponse)(nil),              // 4: ticketscoring.v1.ScoresByTicketResponse
	(*PeriodOverPeriodScoreChangeResponse)(nil), // 5: ticketscoring.v1.PeriodOverPeriodScoreChangeResponse
	(*CategoryScore)(nil),                       // 6: ticketscoring.v1.CategoryScore
	(*AggregatedCategoryScoresResponse)(nil),    // 7: ticketscoring.v1.AggregatedCategoryScoresResponse
	nil,                                         // 8: ticketscoring.v1.TicketScore.CategoryScoresEntry
	(*timestamppb.Timestamp)(nil),               // 9: google.protobuf.Timestamp
}
var file_api_v1_ticketscoring_proto_depIdxs = []int32{
	9,  // 0: ticketscoring.v1.TimePeriodRequest.start_date:type_name -> google.protobuf.Timestamp
	9,  // 1: ticketscoring.v1.TimePeriodRequest.end_date:type_name -> google.protobuf.Timestamp
	8,  // 2: ticketscoring.v1.TicketScore.category_scores:type_name -> ticketscoring.v1.TicketScore.CategoryScoresEntry
	3,  // 3: ticketscoring.v1.ScoresByTicketResponse.ticket_scores:type_name -> ticketscoring.v1.TicketScore
	2,  // 4: ticketscoring.v1.CategoryScore.period_scores:type_name -> ticketscoring.v1.PeriodScore
	6,  // 5: ticketscoring.v1.AggregatedCategoryScoresResponse.category_scores:type_name -> ticketscoring.v1.CategoryScore
	0,  // 6: ticketscoring.v1.TicketScoring.GetOverallQualityScore:input_type -> ticketscoring.v1.TimePeriodRequest
	0,  // 7: ticketscoring.v1.TicketScoring.GetAggregatedCategoryScores:input_type -> ticketscoring.v1.TimePeriodRequest
	0,  // 8: ticketscoring.v1.TicketScoring.GetScoresByTicket:input_type -> ticketscoring.v1.TimePeriodRequest
	0,  // 9: ticketscoring.v1.TicketScoring.GetPeriodOverPeriodScoreChange:input_type -> ticketscoring.v1.TimePeriodRequest
	1,  // 10: ticketscoring.v1.TicketScoring.GetOverallQualityScore:output_type -> ticketscoring.v1.OverallQualityScoreResponse
	7,  // 11: ticketscoring.v1.TicketScoring.GetAggregatedCategoryScores:output_type -> ticketscoring.v1.AggregatedCategoryScoresResponse
	4,  // 12: ticketscoring.v1.TicketScoring.GetScoresByTicket:output_type -> ticketscoring.v1.ScoresByTicketResponse
	5,  // 13: ticketscoring.v1.TicketScoring.GetPeriodOverPeriodScoreChange:output_type -> ticketscoring.v1.PeriodOverPeriodScoreChangeResponse
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_api_v1_ticketscoring_proto_init() }
func file_api_v1_ticketscoring_proto_init() {
	if File_api_v1_ticketscoring_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_ticketscoring_proto_rawDesc), len(file_api_v1_ticketscoring_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_ticketscoring_proto_goTypes,
		DependencyIndexes: file_api_v1_ticketscoring_proto_depIdxs,
		MessageInfos:      file_api_v1_ticketscoring_proto_msgTypes,
	}.Build()
	File_api_v1_ticketscoring_proto = out.File
	file_api_v1_ticketscoring_proto_goTypes = nil
	file_api_v1_ticketscoring_proto_depIdxs = nil
}
