apiVersion: v1
kind: PersistentVolume
metadata:
  name: ticket-quality-db-pv 
spec:
  capacity:
    storage: 1Gi 
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce 
  persistentVolumeReclaimPolicy: Retain 
  storageClassName: standard 
  hostPath:
    path: "/mnt/data/ticket-quality" 
