apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ticket-quality-db-pvc 
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi